# Generated by Django 4.2.2 on 2023-06-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadFileDetails",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("user_id", models.CharField(max_length=100, null=True, unique=True)),
                ("file_name", models.CharField(max_length=200, null=True)),
                ("file_path", models.FileField(upload_to="apps/upload/")),
                ("upload_time", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(max_length=200, null=True)),
                ("error", models.CharField(max_length=200, null=True)),
                ("stored_time", models.DateTimeField(auto_now=True)),
                ("last_updated_time", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
