# Generated by Django 4.2.2 on 2023-06-28 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileStatus",
            fields=[
                (
                    "id",
                    models.SmallIntegerField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("status", models.CharField(max_length=50, null=True)),
            ],
            options={
                "db_table": "file_status",
            },
        ),
        migrations.CreateModel(
            name="FileTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("tempname", models.CharField(max_length=50, null=True)),
                ("storagename", models.CharField(max_length=50, null=True)),
                ("tempstorageloc", models.CharField(max_length=255, null=True)),
                ("blobstorageloc", models.CharField(max_length=255, null=True)),
            ],
            options={
                "db_table": "filetemplate",
            },
        ),
        migrations.CreateModel(
            name="FileTemplateField",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("tempid", models.SmallIntegerField(null=True)),
                ("fieldname", models.CharField(max_length=50, null=True)),
                ("columnPos", models.IntegerField(null=True)),
                ("Allownull", models.BooleanField(default=False)),
                ("Allowempty", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "filetemplatefield",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.SmallIntegerField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("EffemId", models.EmailField(max_length=254)),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="UploadFileDetails",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(max_length=50, null=True)),
                ("UploadedOn", models.DateTimeField(auto_now_add=True)),
                (
                    "ErrorFilePath",
                    models.FileField(
                        default=None,
                        upload_to="apps/upload/error",
                        verbose_name="error_file_path",
                    ),
                ),
                ("CreatedBy", models.SmallIntegerField(null=True)),
                ("CreatedOn", models.DateTimeField(auto_now_add=True)),
                ("LastUpdatedBy", models.SmallIntegerField(null=True)),
                ("LastUpdatedOn", models.DateTimeField(auto_now=True)),
                (
                    "filetempid",
                    models.ForeignKey(
                        db_column="filetemplateid",
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="upload.filetemplate",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        db_column="StatusId",
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="upload.filestatus",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="UploadedBy",
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="upload.user",
                    ),
                ),
            ],
            options={
                "db_table": "uploadfiledetails",
            },
        ),
        migrations.CreateModel(
            name="FileTemplateRule",
            fields=[
                (
                    "id",
                    models.SmallIntegerField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("RuleDefination", models.CharField(max_length=255, null=True)),
                ("CreatedBy", models.SmallIntegerField(null=True)),
                ("CreatedOn", models.DateTimeField(auto_now_add=True)),
                ("LastUpdatedBy", models.SmallIntegerField(null=True)),
                ("LastUpdatedOn", models.DateTimeField(auto_now=True)),
                (
                    "filetempfieldid",
                    models.ForeignKey(
                        db_column="filetempfieldId",
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="upload.filetemplatefield",
                    ),
                ),
                (
                    "filetempid",
                    models.ForeignKey(
                        db_column="filetempid",
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="upload.filetemplate",
                    ),
                ),
            ],
            options={
                "db_table": "FileTemplateRule",
            },
        ),
    ]
