# Generated by Django 4.2.2 on 2023-06-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0002_alter_uploadfiledetails_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadfiledetails",
            name="file_path",
        ),
        migrations.AddField(
            model_name="uploadfiledetails",
            name="file",
            field=models.FileField(
                default="SOME STRING",
                upload_to="apps/upload/",
                verbose_name="file_path",
            ),
        ),
    ]
