# Generated by Django 4.2.2 on 2023-06-27 05:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0003_remove_uploadfiledetails_file_path_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileStatus",
            fields=[
                (
                    "id",
                    models.SmallIntegerField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("status", models.CharField(max_length=50, null=True)),
            ],
            options={
                "db_table": "file_status",
            },
        ),
        migrations.CreateModel(
            name="FileType",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(max_length=50, null=True)),
                (
                    "path",
                    models.FileField(
                        default=None,
                        upload_to="apps/upload/file",
                        verbose_name="file_path",
                    ),
                ),
            ],
            options={
                "db_table": "filetype",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.SmallIntegerField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("EffemId", models.EmailField(max_length=254)),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.RenameField(
            model_name="uploadfiledetails",
            old_name="upload_time",
            new_name="CreatedOn",
        ),
        migrations.RenameField(
            model_name="uploadfiledetails",
            old_name="last_updated_time",
            new_name="LastUpdatedOn",
        ),
        migrations.RemoveField(
            model_name="uploadfiledetails",
            name="error",
        ),
        migrations.RemoveField(
            model_name="uploadfiledetails",
            name="file",
        ),
        migrations.RemoveField(
            model_name="uploadfiledetails",
            name="file_name",
        ),
        migrations.RemoveField(
            model_name="uploadfiledetails",
            name="stored_time",
        ),
        migrations.AddField(
            model_name="uploadfiledetails",
            name="CreatedBy",
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="uploadfiledetails",
            name="ErrorFilePath",
            field=models.FileField(
                default=None,
                upload_to="apps/upload/error",
                verbose_name="error_file_path",
            ),
        ),
        migrations.AddField(
            model_name="uploadfiledetails",
            name="FilePath",
            field=models.FileField(
                default=None, upload_to="apps/upload/file", verbose_name="file_path"
            ),
        ),
        migrations.AddField(
            model_name="uploadfiledetails",
            name="LastUpdatedBy",
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="uploadfiledetails",
            name="UploadedOn",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="uploadfiledetails",
            name="name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name="uploadfiledetails",
            table="uploadfiledetails",
        ),
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.SmallIntegerField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("Rule", models.CharField(max_length=200, null=True)),
                ("CreatedBy", models.SmallIntegerField(null=True)),
                ("CreatedOn", models.DateTimeField(auto_now_add=True)),
                ("LastUpdatedBy", models.SmallIntegerField(null=True)),
                ("LastUpdatedOn", models.DateTimeField(auto_now=True)),
                (
                    "filetypeid",
                    models.ForeignKey(
                        db_column="filetypeid",
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="upload.filetype",
                    ),
                ),
            ],
            options={
                "db_table": "rule",
            },
        ),
        migrations.AddField(
            model_name="uploadfiledetails",
            name="filetypeid",
            field=models.ForeignKey(
                db_column="filetypeid",
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="upload.filetype",
            ),
        ),
        migrations.AlterField(
            model_name="uploadfiledetails",
            name="status",
            field=models.ForeignKey(
                db_column="StatusId",
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="upload.filestatus",
            ),
        ),
        migrations.AlterField(
            model_name="uploadfiledetails",
            name="user_id",
            field=models.ForeignKey(
                db_column="UploadedBy",
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="upload.user",
            ),
        ),
    ]
